"""Reusable Manim helpers for scripts generated by codegen.py.

Keeping this logic here means a generated scene only has to call
`make_node(...)` and `animate_step(...)` with plain data, instead of
each generated file re-declaring the same Manim boilerplate.
"""

from manim import (
    BLUE,
    GRAY,
    GREEN,
    ORANGE,
    PURPLE,
    RED,
    UP,
    WHITE,
    YELLOW,
    Arrow,
    Create,
    FadeIn,
    FadeOut,
    Rectangle,
    Text,
    VGroup,
)

COLOR_MAP = {
    "blue": BLUE,
    "red": RED,
    "green": GREEN,
    "orange": ORANGE,
    "purple": PURPLE,
    "yellow": YELLOW,
    "white": WHITE,
    "gray": GRAY,
    "grey": GRAY,
}

NODE_WIDTH = 2.6
NODE_HEIGHT = 1.2


def resolve_color(color_name):
    return COLOR_MAP.get(color_name, WHITE)


def make_node(label_text, color_name):
    """A labeled rectangle representing one architecture component."""
    color = resolve_color(color_name)
    box = Rectangle(color=color, height=NODE_HEIGHT, width=NODE_WIDTH)
    text = Text(label_text, font_size=24, color=color).move_to(box.get_center())
    return VGroup(box, text)


def animate_step(scene, src_node, dst_node, protocol=None):
    """Animate one flow step: draw an arrow src -> dst, label it with the
    protocol if present, hold briefly, then clear it before the next step."""
    arrow = Arrow(
        src_node.get_center(),
        dst_node.get_center(),
        buff=NODE_WIDTH / 2,
        color=YELLOW,
    )
    animations = [Create(arrow)]
    mobjects = [arrow]
    if protocol:
        label = Text(protocol, font_size=18).next_to(arrow, UP, buff=0.1)
        animations.append(FadeIn(label))
        mobjects.append(label)

    scene.play(*animations)
    scene.wait(0.4)
    scene.play(*[FadeOut(m) for m in mobjects])
